sudo: false
addons:
  firefox: "latest"
before_install:
  # Start a display server where all graphical operations happens in memory
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js: 7
branches:
  only:
    - dev1
    - dev2
    - dev3
    - dev4
    - dev5
    - dev6
notifications:
  email: true
  slack: bluemix-garage-skills:TbJLoFILC1nL93wJlP2F9YMb
before_script:
  ./scripts/merge-from-known-good.sh
script:
  npm run ci
after_success:
  ./scripts/merge-to-known-good.sh
before_deploy:
  npm pack
deploy:
  edge: true
  provider: bluemixcloudfoundry
  username: wgpannel@us.ibm.com
  password: (1ny@3cCLNYABC
  organization: BMXEDU
  space: garage-bootcamp-dev
  manifest: manifest-dev.yml
  region: ng
  api: https://api.ng.bluemix.net
  on:
    branch: dev6
    branch: dev5
    branch: dev4
    branch: dev3
    branch: dev2
    branch: dev1

