sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js: 7
branches:
  only:
    - dev1
    - dev2
    - dev3
    - dev4
    - dev5
    - dev6
notifications:
  email: true
before_script:
  ./scripts/merge-from-known-good.sh
script:
  npm run ci
after_success:
  ./scripts/merge-to-known-good.sh
before_deploy:
  npm pack
