---
stages:
  - name: dev
    inputs:
      - type: git
        branch: dev1
        service: ${SOURCE_CONTROL_SERVICE}
    triggers:
      - type: commit
    jobs:
      - name: distribution
        type: builder
        artifact_dir: archive
        enable_tests: true
        test_file_pattern: '*.xml, generated/*.xml'
        build_type: npm
        script: |-
          #!/bin/bash
          printenv
          ls -al

          git config --global user.email "wgpannel@us.ibm.com"
          git config --global user.name "wil.pannell"

          git branch integration
          git fetch origin integration
          git merge integration --ff-only

          echo 'build distribution'
          export PATH=/opt/IBM/node-v6.7.0/bin:./node_modules/.bin:$PATH
          npm install
          npm run ci
          npm run dist

          echo 'build archive'
          mkdir -p archive
          mkdir -p generated
          scripts/archive.sh
          git log -1 --pretty > archive/changelog.txt

          echo 'merge to known good branch'
          git checkout integration
          git pull origin integration
          git merge dev1 --no-ff --log
          git push origin integration

          echo 'tag distribution'
          git branch distribution
          git fetch origin distribution
          git checkout distribution
          git pull origin distribution

          cp archive/dist.tar.gz .
          cp archive/changelog.txt .

          git add .
          git commit -m "$(cat archive/changelog.txt)"
          git push origin distribution

          echo 'tag archive'
          git branch archive
          git fetch origin archive
          git checkout archive
          git pull origin archive

          cp archive/archive.tar.gz .
          cp archive/changelog.txt .

          git add .
          git commit -m "$(cat archive/changelog.txt)"
          git push origin archive
